### ISSUE TITLE
Backup fails every time after first

### ISSUE THREAD

**Issue by nathanrsxtn** [Silly511/Backups-Mod#26]
Anytime a backup is attempted when `/backupsmod/world/Last` is present the backup fails with this or a similar error (the filename is not always `Village.dat.gz`).
```
[14:16:39] [Server thread/INFO] [backups]: Starting backup
[14:16:39] [Server thread/INFO] [backups]: Disabling world saving
[14:16:40] [Backup Thread/ERROR] [backups]: Backup failed
java.nio.file.FileSystemException: backupsmod/world/In-Progress/data/Village.dat.gz -> backupsmod/world/2020-4-1 14-13-44/data/Village.dat.gz: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_241]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_241]
	at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:476) ~[?:1.8.0_241]
	at java.nio.file.Files.createLink(Files.java:1086) ~[?:1.8.0_241]
	at silly511.backups.helpers.BackupHelper.backup(BackupHelper.java:74) ~[BackupHelper.class:?]
	at silly511.backups.BackupManager$BackupThread.run(BackupManager.java:195) [BackupManager$BackupThread.class:?]
[14:16:40] [Server thread/INFO] [backups]: Restoring world saving
```
Deleting `/backupsmod/world/Last` solves the error only for the next backup. The file has to be deleted again to successfully backup.
Running Forge Server 1.12.2 14.23.5.2847 (DietPi OS)

**Comment by Fadenfire** [comment]
What file system are you using?

**Comment by nathanrsxtn** [comment]
The server is on a VFAT external USB hard disk.

**Comment by Fadenfire** [comment]
FAT doesn't support hard links, which my mod relies on to work. I suggest you use a different backup mod, like [FTB Backups](https://www.curseforge.com/minecraft/mc-mods/ftb-backups).
