### ISSUE TITLE
Error loading backup on 1.12.2 server

### ISSUE THREAD

**Issue by JOZA-ORANGE** [Silly511/Backups-Mod#37]
When I use the command to restore the backup, the console will throw an error message.
The backup file exists and is available, but an error will be reported when executing the restore command

The following are some server operation logs:
```
[12:30:40] [Server thread/INFO]: JOZA_ORANGE issued server command: /backupsmod restoreworld 2022/8/17-12:29:26
[12:30:40] [Server thread/WARN]: Couldn't process command: backupsmod restoreworld 2022/8/17-12:29:26
java.lang.IllegalStateException: Unable to find server shutdown hook
        at silly511.backups.commands.RestoreWorldCommandServer.func_184881_a(RestoreWorldCommandServer.java:70) ~[RestoreWorldCommandServer.class:?]
        at silly511.backups.commands.BackupsModCommand.func_184881_a(BackupsModCommand.java:92) ~[BackupsModCommand.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:127) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [bj.class:?]
        at catserver.server.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:51) [CraftSimpleCommandMap.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchVanillaCommand(CraftServer.java:721) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:716) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1667) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1468) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_333]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_333]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]
```

**Comment by Fadenfire** [comment]
Unfortunately, it seems that the backup restore feature is incompatible with CatServer. You can still restore backups using the command line restore. Open a command prompt and then run the command `java -jar <path to mod file> <backup dir> <world dir>` to restore the backup over the world.
