### ISSUE TITLE
Backups spontaneously failing about an hour into a new world [Tekkit 2, no modifications]

### ISSUE THREAD

**Issue by OpenSauce04** [Silly511/Backups-Mod#38]
```
[22:44:22] [Client thread/INFO]: [CHAT] [Backups]: Started backup
[22:44:23] [Backup Thread/INFO]: Flushing world data to disk
[22:44:23] [Backup Thread/INFO]: Trimming old backups
[22:44:23] [Backup Thread/INFO]: Creating backup
[22:44:23] [Backup Thread/ERROR]: Backup failed
java.nio.file.FileSystemException: backups\Global Warming 2\In-Progress\data\ArboristTracker.common.dat.gz -> backups\Global Warming 2\2022-8-27 22-10-50\data\ArboristTracker.common.dat.gz: Incorrect function.

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_51]
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_51]
    at sun.nio.fs.WindowsFileSystemProvider.createLink(WindowsFileSystemProvider.java:608) ~[?:1.8.0_51]
    at java.nio.file.Files.createLink(Files.java:1086) ~[?:1.8.0_51]
    at silly511.backups.helpers.BackupHelper.backup(BackupHelper.java:69) ~[BackupHelper.class:?]
    at silly511.backups.BackupManager$BackupThread.run(BackupManager.java:223) [BackupManager$BackupThread.class:?]
[22:44:23] [Server thread/INFO]: Restoring world saving
[22:44:23] [Client thread/INFO]: [CHAT] [Backups]: Backup failed! Check log for more details
```

**Comment by Fadenfire** [comment]
Where is your minecraft directory located? Is it on a different drive than your `C:` drive?

**Comment by OpenSauce04** [comment]
Yes, I'm running through an ATLauncher instance
`I:\ATLauncher\instances\Tekkit2`

**Comment by OpenSauce04** [comment]
It's worth noting that backups work fine on new worlds and can be loaded and everything, but spontaneously break after a while, and once the break, they are permanently broken
![image](https://user-images.githubusercontent.com/48618519/187083762-58e4431a-71be-4134-8eea-e043a1b25250.png)
I'm pretty sure that this is not caused by what drive the game is on because of this

**Comment by Fadenfire** [comment]
What filesystem is your `I:` drive using? Is it something other than NTFS? My backups mod uses hardlinks to de-duplicate files in the backup, so whatever filesystem you're using needs to support hardlinks.

**Comment by OpenSauce04** [comment]
Ah yes, I was running on an exFat drive
I will reformat it to NTFS
I had no idea that could break the mod

**Comment by Fadenfire** [comment]
Yeah, I should probably put that somewhere in the description of the mod.
